- name: Useful stuff
  apt:
    name: ['unzip', 'wget', 'curl', 'git', 'vim', 'make', 'build-essential', 'openjdk-11-jre']
    update_cache: yes

- name: Install http-echo
  unarchive:
    src: https://github.com/hashicorp/http-echo/releases/download/v0.2.3/http-echo_0.2.3_linux_amd64.zip
    dest: /usr/local/bin/
    remote_src: yes
    creates: /usr/local/bin/http-echo

- name: Install packages to allow `apt` to use a repository over HTTPS
  apt:
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common']
    update_cache: yes

- name: Add Docker’s official GPG key
  apt_key:
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Create the `docker` group
  group:
    name: docker
    state: present

- name: Add your user to the `docker` group.
  user:
    append: yes
    groups:
      - docker
    name: "{{ ansible_user }}"

- name: Install docker
  apt:
    name: ['docker-ce', 'docker-ce-cli', 'containerd.io', 'python-docker']
    update_cache: yes

- name: Start docker
  systemd:
    name: docker
    state: started
    enabled: yes

- name: iptables
  shell: iptables-restore
  args:
    stdin: "{{ lookup('template', 'rules.v4.j2' ) }}"
