---
- name: Ensure group "consul" exists
  group:
    name: consul
    state: present

- name: Create consul user
  user:
    name: consul
    group: consul
    create_home: no

- name: Install consul/nomad/vault
  unarchive:
    src: "{{ item.url }}"
    dest: "{{ bin_path }}"
    remote_src: yes
    creates: "{{ item.bin }}"
  with_items:
    - bin: "{{ consul_bin }}"
      url: "{{ consul_precompiled_bin }}"
    - bin: "{{ nomad_bin }}"
      url: "{{ nomad_precompiled_bin }}"
    - bin: "{{ vault_bin }}"
      url: "{{ vault_precompiled_bin }}"

- name: Ensure nomad/vault dirs
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ nomad_config_path }}"
    - "{{ nomad_data_dir }}"
    - "{{ vault_config_path }}"
    - "{{ vault_data_dir }}"

- name: Ensure nomad services dirs
  file:
    path: "{{ nomad_services_dir }}/{{ item }}"
    state: directory
    recurse: yes
    mode: '0777'
  with_items: "{{ nomad_services }}"

- name: Allow consul group to access consul_data_dir
  file:
    path: "{{ item }}"
    state: directory
    group: consul
    owner: consul
  with_items:
    - "{{ consul_config_path }}"
    - "{{ consul_data_dir }}"

- name: Consul/Nomad/Vault config
  template:
    src: "{{ lookup('vars', item + '_config_template') }}"
    dest: "{{ lookup('vars', item + '_config') }}"
  with_items:
    - consul
    - nomad
    - vault

- name: Add consul/nomad to sysytemd
  template:
    src: "{{ item }}-agent.service.j2"
    dest: /etc/systemd/system/{{ item }}.service
  with_items:
    - consul
    - nomad

- name: Add vault to sysytemd
  template:
    src: vault-server.service.j2
    dest: /etc/systemd/system/vault.service

- name: Start consul/nomad/vault
  systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
    enabled: yes
  with_items:
    - consul
    - nomad
    - vault

- include_tasks: vault.yml
